Fix doc build in Kali
build fails because LANG is undefined
./Documentation/sphinx/parse-headers.pl include/uapi/linux/dvb/net.h /<<PKGBUILDDIR>>/debian/build/build-doc/Documentation/output/net.h.rst ./Documentation/userspace-api/media/net.h.rst.exceptions
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
./Documentation/sphinx/parse-headers.pl include/uapi/linux/videodev2.h /<<PKGBUILDDIR>>/debian/build/build-doc/Documentation/output/videodev2.h.rst ./Documentation/userspace-api/media/videodev2.h.rst.exceptions
	LANGUAGE = (unset),
	LC_ALL = (unset),
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LC_COLLATE = "C",
	LANGUAGE = (unset),
	LC_NUMERIC = "C",
	LC_ALL = (unset),
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
	LC_COLLATE = "C",
perl: warning: Falling back to the standard locale ("C").
	LC_NUMERIC = "C",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
[...]
perl: warning: Falling back to the standard locale ("C").
Traceback (most recent call last):
  File "/usr/share/sphinx/scripts/python3/sphinx-build", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3/dist-packages/sphinx/cmd/build.py", line 326, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.11/locale.py", line 626, in setlocale
    return _setlocale(category, locale)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
locale.Error: unsupported locale setting
make[5]: *** [Documentation/Makefile:132: xmldocs] Error 1